### ISSUE TITLE
Icons not loading post-upgrade

### ISSUE THREAD

**Issue by jackyaz** [linuxserver/Heimdall#290]
Did I mess something up? All icons report the below since upgrade to 2.1.6 from 2.1.2

/storage/supportedapps/jackett.png
Request Method: GET
Status Code: 404 Not Found

**Comment by jackyaz** [comment]
Application type only lists None

Docker log (using Linuxserver container) is spamming this for Heimdall:


[2018-11-06 09:02:37][552] Failed:     App\Jobs\ProcessApps


[2018-11-06 09:03:37][553] Processing: App\Jobs\ProcessApps


[2018-11-06 09:03:38][554] Processing: App\Jobs\ProcessApps


[2018-11-06 09:03:38][555] Processing: App\Jobs\ProcessApps


[2018-11-06 09:03:38][555] Failed:     App\Jobs\ProcessApps

**Comment by KodeStar** [comment]
Go to /config/www/SupportedApps and delete everything in there

**Comment by jackyaz** [comment]
Will this result in any re-configuration of my current apps?

**Comment by jackyaz** [comment]
Oddly, /config/www/SupportedApps is already empty

**Comment by jackyaz** [comment]
Removed app.sqlite still no application type or icons

**Comment by KodeStar** [comment]
if /config/www/SupportedApps is empty grab the zip from https://github.com/linuxserver/Heimdall-Apps/archive/master.zip and extract the contents into there.  The issue came about because the folder wasn't persistant, that's been fixed but I think it's confusing itself.

**Comment by jackyaz** [comment]
Folder contents added, restarted Heimdall and still no dice :(

**Comment by KodeStar** [comment]
Try now, it seems github and the applist disagreed on the capitalisation of nzbget, click the update apps list

**Comment by marcinozga** [comment]
Icons are still not loading when adding new apps. The problem is with icon path, it points to /storage/supportedapps/icon.png or .svg, where in fact icons are in /storage/supportedapps/appname/icon.png

**Comment by KodeStar** [comment]
Do you have the latest version of the docker?

1. Both those urls are wrong
2. My guess is you haven't gone to items and clicked the Update apps list button.
3. While icons do exist at `/app/SupportedApps/`appname/icon.png, that isn't a publicly accessible url
4. `/storage/supportedapps/icon.png` is an old url, but that folder wasn't persistent
5. The new url should be `/storage/icons/icon.png` which is a persistent folder

**Comment by marcinozga** [comment]
Yes, I have the latest version. I did click update apps button, multiple times. My supportedapps folder was empty this morning and Heimdall wasn't working at all, I had to pull master from Heimdall-Apps and extract it there. I'm looking at errors in chrome dev tools, and it's showing those paths right now.

**Comment by KodeStar** [comment]
Try emptying the supportedapps folder and running it again

**Comment by marcinozga** [comment]
It's pulling 3 random apps at a time after hitting update button. But the paths are still pointing supportedapps folders.

**Comment by KodeStar** [comment]
Go to settings, what version of the app does it say it is?

**Comment by marcinozga** [comment]
2.1.8

**Comment by marcinozga** [comment]
It works after wiping database. Is there a way to export existing apps? Manually recreating all is not my idea of fun.

**Comment by KodeStar** [comment]
No idea then, 2.1.8 does a replace on supportedapps to icons to try and help people who haven't gone into the items to update the application type, so if you are seeing supportedapps I have no idea, but that's definitely not the behaviour I see on any of my versions.  Hard to fix if I can't replicate.

**Comment by KodeStar** [comment]
Did you go into each Item and select the application type from the dropdown?  If not that would explain why it wasn't working for you.  I realise looking at the thread that was specifically said in this thread, but it was in the linked comment `Go into each item and make sure the correct app is specified in the dropdown next to the item name, if not change it, if it is try changing it to something else then back again.`

**Comment by marcinozga** [comment]
Yes, I did, yesterday. But something apparently broke overnight, because supportedapps folder was empty and Heimdall wasn't working at all.

**Comment by KodeStar** [comment]
Yeah, that was when the folder wasn't persistant, you probably need to do it again

**Comment by PeterXQChen** [comment]
Im facing the same issue on a new install. icons folder do not have icons. symlink also not automatically made.

**Comment by jackyaz** [comment]
Fresh install, still no icons/supportedapps empty

I notice that it reaches out to 212.83.139.18, could the site be misconfigured?

**Comment by KodeStar** [comment]
Are you copying the app.sqlite folder back in?

**Comment by jackyaz** [comment]
Nope, spun up a new container with separate sotrage/config

**Comment by KodeStar** [comment]
https://sqlitebrowser.org/ download that, point it to the database, then browse failed_jobs.

**Comment by jackyaz** [comment]
Ah I wonder if this is my self-signed certs - I wouldn't have thought that'd affect downloading apps?

```
RuntimeException: Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed
[file] /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(): Failed to enable crypto
[file] /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(https://apps.heimdall.site/list): failed to open stream: operation failed
[file] /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323 in /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(334): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(51): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Middleware.php(58): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#10 /var/www/localhost/heimdall/app/SupportedApps.php(105): GuzzleHttp\Client->request('GET', 'https://apps.he...')
#11 /var/www/localhost/heimdall/app/Jobs/ProcessApps.php(35): App\SupportedApps::getList()
#12 [internal function]: App\Jobs\ProcessApps->handle()
#13 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#14 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#18 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ProcessApps))
#19 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessApps))
#20 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ProcessApps), false)
#22 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#23 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#24 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#25 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#26 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#27 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#28 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#29 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#30 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#31 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#32 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#33 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#34 /var/www/localhost/heimdall/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#35 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#36 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/localhost/heimdall/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 {main}

Next GuzzleHttp\Exception\RequestException: Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed
[file] /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(): Failed to enable crypto
[file] /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(https://apps.heimdall.site/list): failed to open stream: operation failed
[file] /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323 in /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:52
Stack trace:
#0 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(67): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Psr7\Request), Object(RuntimeException))
#1 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#2 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Middleware.php(58): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#9 /var/www/localhost/heimdall/app/SupportedApps.php(105): GuzzleHttp\Client->request('GET', 'https://apps.he...')
#10 /var/www/localhost/heimdall/app/Jobs/ProcessApps.php(35): App\SupportedApps::getList()
#11 [internal function]: App\Jobs\ProcessApps->handle()
#12 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#17 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ProcessApps))
#18 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessApps))
#19 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ProcessApps), false)
#21 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#22 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#23 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#24 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#25 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#26 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#27 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#28 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#29 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#31 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#32 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#33 /var/www/localhost/heimdall/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#34 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#35 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/localhost/heimdall/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 {main}
```

**Comment by jackyaz** [comment]
Removed #openssl.cafile = /config/complete.pem
 from php-local.ini and now all good

How to use SSL certs and not break apps, I suppose is the next question?

**Comment by KodeStar** [comment]
Maybe this? https://github.com/linuxserver/Heimdall#self-signed-certificates-and-local-cas

**Comment by jackyaz** [comment]
Just in the process of dumping ca-certs into my PEM file as we speak

**Comment by jackyaz** [comment]
Bingo, combined the /etc/ssl/certs/ca-certificates.crt with my CA/cert chain and all good!
