### ISSUE TITLE
Undefined property: stdClass::$username

### ISSUE THREAD

**Issue by twolaw** [linuxserver/Heimdall#417]
Heimdall version 2.2.2
Linuxserver docker on LibreElec (linux) aarch64

When I click on edit button of ruTorrent item I get the following error page:

```
 ErrorException (E_ERROR)
Undefined property: stdClass::$username (View: /config/www/SupportedApps/ruTorrent/config.blade.php)
 (View: /config/www/SupportedApps/ruTorrent/config.blade.php)
 (View: /config/www/SupportedApps/ruTorrent/config.blade.php)
```

log:
```
#52 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /var/www/localhost/heimdall/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"} 
[2019-12-08 12:56:38] laravel.ERROR: Undefined property: stdClass::$username (View: /config/www/SupportedApps/ruTorrent/config.blade.php) (View: /config/www/SupportedApps/ruTorrent/config.blade.php) (View: /config/www/SupportedApps/ruTorrent/config.blade.php) {"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$username (View: /config/www/SupportedApps/ruTorrent/config.blade.php) (View: /config/www/SupportedApps/ruTorrent/config.blade.php) (View: /config/www/SupportedApps/ruTorrent/config.blade.php) at /var/www/localhost/heimdall/storage/framework/views/0599c0d1b8b0298103049c06993d94fcbddddd10.php:10, ErrorException(code: 0): Undefined property: stdClass::$username (View: /config/www/SupportedApps/ruTorrent/config.blade.php) (View: /config/www/SupportedApps/ruTorrent/config.blade.php) at /var/www/localhost/heimdall/storage/framework/views/0599c0d1b8b0298103049c06993d94fcbddddd10.php:10, ErrorException(code: 0): Undefined property: stdClass::$username (View: /config/www/SupportedApps/ruTorrent/config.blade.php) at /var/www/localhost/heimdall/storage/framework/views/0599c0d1b8b0298103049c06993d94fcbddddd10.php:10, ErrorException(code: 0): Undefined property: stdClass::$username at /var/www/localhost/heimdall/storage/framework/views/0599c0d1b8b0298103049c06993d94fcbddddd10.php:10)
[stacktrace]
#0 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/localh...', Array)
#2 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/localh...', Array)
```
In the past, I could edit it normally but today this error page appears and I can't edit the ruTorrent item.
I have 7 items in Heimdall, only this one raises this error.

![error username heimdall](https://user-images.githubusercontent.com/10365746/70390820-e4c08100-19ce-11ea-840d-251880042b69.png)

**Comment by KodeStar** [comment]
Can you delete and re-add? I think this one has been updated and my guess is username wasn't an option when you first created the tile and has been added afterwards.

**Comment by KodeStar** [comment]
Actually scratch that, I'll make a quick change to that code.

**Comment by KodeStar** [comment]
Ok, press the update apps button and let me know if that resolves it (or changes the error)

**Comment by twolaw** [comment]
It worked.
Problem solved, thank you!

**Comment by ThatComputerKid** [comment]
I had this same error with Jellyfin it and is still broken.

**Comment by tedr56** [comment]
> 
> 
> I had this same error with Jellyfin it and is still broken.

The optional config fields have to be set to access Jellyfin settings back again.

**Comment by KodeStar** [comment]
If this is still an issue with jellyfin add a new issue
