### ISSUE TITLE
Fresh Ubuntu 21.10 Install: PHP 8.0 throws Fatal error with Heimdall

### ISSUE THREAD

**Issue by SaintFenix** [linuxserver/Heimdall#629]
This has been discussed before, but Heimdall doesn't function on PHP 8.0 and Ubuntu has made that the default PHP in the repositories.

Here is the error Heimdall throws when attempting to open it with PHP artisan on PHP 8.0:

```
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php:838
Stack trace:
#0 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(838): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(807): Illuminate\Container\Container->resolveDependencies()
#2 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build()
#3 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve()
#4 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->make()
#5 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(264): Illuminate\Foundation\Application->make()
#6 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\Container\Container->Illuminate\Container\{closure}()
#7 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build()
#8 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve()
#9 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->make()
#10 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Foundation\Application->make()
#11 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#12 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#13 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#14 {main}
  thrown in /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 838
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php:838
Stack trace:
#0 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(838): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(807): Illuminate\Container\Container->resolveDependencies()
#2 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build()
#3 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve()
#4 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->make()
#5 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(264): Illuminate\Foundation\Application->make()
#6 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\Container\Container->Illuminate\Container\{closure}()
#7 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build()
#8 /home/fenix/Git/Heimdall-2.2.2/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve()
```

===========================================

For anyone reading I figured out a workaround with these commands for Ubuntu 21.10:

There is a repository available that has older versions of PHP:
`sudo add-apt-repository -y ppa:ondrej/php`

We then need to edit the sources list to allow installation of the older .debs on Impish:
`sudo nano /etc/apt/sources.list.d/ondrej-ubuntu-php-impish.list`

we replace the top line with:
deb http://ppa.launchpad.net/ondrej/php/ubuntu/ focal main

and lastly we need to install PHP 7.4:
`sudo apt install php7.4 php7.4-sqlite3`

I'm only comfortable with doing this due to this being a fun project on a vm disconnected from the world. I don't know the security ramifications otherwise of downgrading it, but I wouldn't be comfortable doing so on a public facing computer.

**Comment by hockeymikey** [comment]
@aptalca Why

**Comment by ntaylor-86** [comment]
@hockeymikey Docker is a way to guarantee that Heimdall is running in the same environment that it was developed for. So you don't get these kind of dependency issues 👍

**Comment by hockeymikey** [comment]
@ntaylor-86 No, I know what docker is, why can't they fix it? I'm not going to add overhead just to run Heimdall, I'll ditch it and find something that isn't outdated.

**Comment by aptalca** [comment]
Why don't you fix it? It's open source. PRs welcome.

**Comment by ntaylor-86** [comment]
Working on upgrading laravel from 5.7 to possibly 7.0 to support php 8.0.
I've done the 5.7 to 6.0 upgrade here -> https://github.com/ntaylor-86/Heimdall/commit/8aa89c6c91e1538627fb3daa1dd040d9135a864f
There are a bunch of changes as the `vendor/` folder has been removed from the `.gitignore`

**Comment by j0nnymoe** [comment]
Heimdall focus moved onto a rewritea while ago https://github.com/linuxserver/heimdalljs

**Comment by ntaylor-86** [comment]
LOL, so you're saying don't waste your time here?

**Comment by ZARk-be** [comment]
@ntaylor-86 > I was about to start working on forking and upgrading to a more recent laravel.
I'm okay to join forces with you if you're still working on it.

**Comment by KodeStar** [comment]
@ZARk-be @ntaylor-86 the current master is based on laravel 7.0 and will soon be released as the next version, feel free to see if I've missed anything
